.TH "src Directory Reference" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchecker_pids\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchecker_pids\&.h\fP"
.br
.ti -1c
.RI "file \fBclient_main\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.ti -1c
.RI "file \fBconnections\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconnections\&.h\fP"
.br
.ti -1c
.RI "file \fBdispatch_cfg\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdispatch_cfg\&.h\fP"
.br
.ti -1c
.RI "file \fBdispatch_main\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdispatcher\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdispatcher\&.h\fP"
.br
.ti -1c
.RI "file \fBgetcfgfile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgetcfgfile\&.h\fP"
.br
.ti -1c
.RI "file \fBipclib\&.cpp\fP"
.br
.ti -1c
.RI "file \fBipclib\&.h\fP"
.br
.ti -1c
.RI "file \fBprotocol_msg\&.h\fP"
.br
.ti -1c
.RI "file \fBSocket\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSocket\&.h\fP"
.br
.ti -1c
.RI "file \fBthread_pair\&.cpp\fP"
.br
.ti -1c
.RI "file \fBthread_pair\&.h\fP"
.br
.ti -1c
.RI "file \fBtuxcli_main\&.cpp\fP"
.br
.in -1c
