.TH "all_dispatch_cfg" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
all_dispatch_cfg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dispatch_cfg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBall_dispatch_cfg\fP ()=delete"
.br
.ti -1c
.RI "\fBall_dispatch_cfg\fP (const Json::Value json)"
.br
.ti -1c
.RI "\fBall_dispatch_cfg\fP (\fBall_dispatch_cfg\fP const &)=delete"
.br
.ti -1c
.RI "\fBall_dispatch_cfg\fP (\fBall_dispatch_cfg\fP &&)=delete"
.br
.ti -1c
.RI "\fBall_dispatch_cfg\fP & \fBoperator=\fP (\fBall_dispatch_cfg\fP const &)=delete"
.br
.ti -1c
.RI "\fBall_dispatch_cfg\fP & \fBoperator=\fP (\fBall_dispatch_cfg\fP &&)=delete"
.br
.ti -1c
.RI "\fB~all_dispatch_cfg\fP ()=default"
.br
.ti -1c
.RI "const Json::Value & \fBget_json\fP () const"
.br
.ti -1c
.RI "void \fBload_all_info\fP ()"
.br
.ti -1c
.RI "void \fBcreate_cfg_values\fP (std::string file_dir)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "void \fBshow_all_config\fP ()"
.br
.ti -1c
.RI "int \fBget_num_dispatchers\fP () const"
.br
.ti -1c
.RI "std::vector< \fBdispatch_cfg\fP > & \fBget_all_dispatch_info\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetNumDispatchers\fP () const"
.br
.ti -1c
.RI "const char * \fBgetDispatcherXX_IP\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "int \fBgetDispatcherXX_Port\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "int \fBgetDispatcherXX_NumThreads\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "const char * \fBgetDispatcherXX_TuxCliProg\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "const char * \fBgetDispatcherXX_TuxCliSetup\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "int \fBgetDispatcherXX_LogLevel\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "int \fBgetDispatcherXX_MaxConnections\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "int \fBgetDispatcherXX_StopTimeout\fP (const std::string dispatchXX) const"
.br
.ti -1c
.RI "const char * \fBgetDispatcherXX_IpcFile\fP (const std::string dispatchXX) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Json::Value \fB_m_json\fP"
.br
.ti -1c
.RI "int \fBNumDispatchers\fP {0}"
.br
.ti -1c
.RI "std::vector< \fBdispatch_cfg\fP > \fBdispatchers_cfg\fP"
.br
.ti -1c
.RI "bool \fBloaded\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of all Dispatchers configuration\&. 
.PP
Definition at line \fB60\fP of file \fBdispatch_cfg\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "all_dispatch_cfg::all_dispatch_cfg ()\fC [delete]\fP"

.SS "all_dispatch_cfg::all_dispatch_cfg (const Json::Value json)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB79\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "all_dispatch_cfg::all_dispatch_cfg (\fBall_dispatch_cfg\fP const &)\fC [delete]\fP"

.SS "all_dispatch_cfg::all_dispatch_cfg (\fBall_dispatch_cfg\fP &&)\fC [delete]\fP"

.SS "all_dispatch_cfg::~all_dispatch_cfg ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void all_dispatch_cfg::create_cfg_values (std::string file_dir)"

.PP
Definition at line \fB38\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "std::vector< \fBdispatch_cfg\fP > & all_dispatch_cfg::get_all_dispatch_info ()\fC [inline]\fP"

.PP
Definition at line \fB99\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "const Json::Value & all_dispatch_cfg::get_json () const\fC [inline]\fP"

.PP
Definition at line \fB87\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int all_dispatch_cfg::get_num_dispatchers () const\fC [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "const char * all_dispatch_cfg::getDispatcherXX_IP (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB64\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "const char * all_dispatch_cfg::getDispatcherXX_IpcFile (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB104\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getDispatcherXX_LogLevel (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB89\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getDispatcherXX_MaxConnections (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB94\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getDispatcherXX_NumThreads (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB74\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getDispatcherXX_Port (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB69\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getDispatcherXX_StopTimeout (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB99\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "const char * all_dispatch_cfg::getDispatcherXX_TuxCliProg (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB79\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "const char * all_dispatch_cfg::getDispatcherXX_TuxCliSetup (const std::string dispatchXX) const\fC [private]\fP"

.PP
Definition at line \fB84\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "int all_dispatch_cfg::getNumDispatchers () const\fC [private]\fP"

.PP
Definition at line \fB59\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "void all_dispatch_cfg::load_all_info ()"

.PP
Definition at line \fB5\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SS "all_dispatch_cfg::operator bool () const\fC [inline]\fP"

.PP
Definition at line \fB93\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "\fBall_dispatch_cfg\fP & all_dispatch_cfg::operator= (\fBall_dispatch_cfg\fP &&)\fC [delete]\fP"

.SS "\fBall_dispatch_cfg\fP & all_dispatch_cfg::operator= (\fBall_dispatch_cfg\fP const &)\fC [delete]\fP"

.SS "void all_dispatch_cfg::show_all_config ()"

.PP
Definition at line \fB109\fP of file \fBdispatch_cfg\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Json::Value all_dispatch_cfg::_m_json\fC [private]\fP"

.PP
Definition at line \fB62\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "std::vector<\fBdispatch_cfg\fP> all_dispatch_cfg::dispatchers_cfg\fC [private]\fP"

.PP
Definition at line \fB64\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "bool all_dispatch_cfg::loaded {false}\fC [private]\fP"

.PP
Definition at line \fB65\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int all_dispatch_cfg::NumDispatchers {0}\fC [private]\fP"

.PP
Definition at line \fB63\fP of file \fBdispatch_cfg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
