.TH "allowed_ips" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
allowed_ips
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dispatcher\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtrace\fP {false}"
.br
.ti -1c
.RI "bool \fBallowed\fP {true}"
.br
.ti -1c
.RI "in_addr \fBip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBdispatcher\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool allowed_ips::allowed {true}"

.PP
Definition at line \fB23\fP of file \fBdispatcher\&.h\fP\&.
.SS "in_addr allowed_ips::ip"

.PP
Definition at line \fB24\fP of file \fBdispatcher\&.h\fP\&.
.SS "bool allowed_ips::trace {false}"

.PP
Definition at line \fB22\fP of file \fBdispatcher\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
