.TH "checker_struct" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
checker_struct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <checker_pids\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::function< int()> \fB_caller\fP"
.br
.ti -1c
.RI "time_t \fB_last_fork\fP {0}"
.br
.ti -1c
.RI "pid_t \fB_pid\fP {0}"
.br
.ti -1c
.RI "std::string \fB_procname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Process struct 
.PP
Definition at line \fB27\fP of file \fBchecker_pids\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::function<int()> checker_struct::_caller"

.PP
Definition at line \fB29\fP of file \fBchecker_pids\&.h\fP\&.
.SS "time_t checker_struct::_last_fork {0}"

.PP
Definition at line \fB30\fP of file \fBchecker_pids\&.h\fP\&.
.SS "pid_t checker_struct::_pid {0}"

.PP
Definition at line \fB31\fP of file \fBchecker_pids\&.h\fP\&.
.SS "std::string checker_struct::_procname"

.PP
Definition at line \fB32\fP of file \fBchecker_pids\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
