.TH "connections" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connections
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connections\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnections\fP (int MaxConnections, int NumThreads)"
.br
.ti -1c
.RI "void \fBmark_obsolete\fP (int idx)"
.br
.ti -1c
.RI "void \fBdelete_obsolete\fP (int idx)"
.br
.ti -1c
.RI "int \fBclean_repeated_ip\fP (sockaddr_in *ppal, \fBSemaphore\fP &sem)"
.br
.ti -1c
.RI "int \fBregister_new_conn\fP (int nthread, int sd, sockaddr_in s_in, \fBSemaphore\fP &sem)"
.br
.ti -1c
.RI "int \fBunregister_conn\fP (int idx, \fBSemaphore\fP &sem)"
.br
.ti -1c
.RI "int \fBending_operation\fP (int idx, \fBSemaphore\fP &sem, \fBconnection\fP &cur_conn)"
.br
.ti -1c
.RI "int \fBcheck_obsolete\fP (int idx_con, \fBSemaphore\fP &sem)"
.br
.ti -1c
.RI "bool \fBis_all_connections_done\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBinitialized\fP {false}"
.br
.ti -1c
.RI "int \fBfirst_free\fP {0}"
.br
.ti -1c
.RI "int \fBnThreads\fP {0}"
.br
.ti -1c
.RI "int \fBMaxConn\fP {0}"
.br
.ti -1c
.RI "\fBconnection\fP * \fBcurrent_connections\fP {nullptr}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Connections class\&. 
.PP
Definition at line \fB31\fP of file \fBconnections\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "connections::connections (int MaxConnections, int NumThreads)"
connections Constructor
.PP
\fBParameters\fP
.RS 4
\fIMaxConnections\fP Max number of connections\&. 
.br
\fINumThreads\fP = Number of thread pairs running 
.RE
.PP

.PP
Definition at line \fB3\fP of file \fBconnections\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int connections::check_obsolete (int idx_con, \fBSemaphore\fP & sem)"
if connection[idx_con] is obsolete marks it as st_obsolete=2\&.
.PP
\fBParameters\fP
.RS 4
\fIidx\fP Index on connection array 
.br
\fIsem\fP \fBSemaphore\fP to lock to avoid data races\&. 
.RE
.PP

.PP
Definition at line \fB123\fP of file \fBconnections\&.cpp\fP\&.
.SS "int connections::clean_repeated_ip (sockaddr_in * ppal, \fBSemaphore\fP & sem)"
Clean repeated IP in connection array\&.
.PP
\fBParameters\fP
.RS 4
\fIppal\fP sockaddr_in data (IP:port) 
.br
\fIsem\fP \fBSemaphore\fP to lock to avoid data races\&. 
.RE
.PP

.PP
Definition at line \fB65\fP of file \fBconnections\&.cpp\fP\&.
.SS "void connections::delete_obsolete (int idx)"

.PP
Definition at line \fB33\fP of file \fBconnections\&.cpp\fP\&.
.SS "int connections::ending_operation (int idx, \fBSemaphore\fP & sem, \fBconnection\fP & cur_conn)"
Sets connection operation info: add 1 to operation counter, gets time
.PP
\fBParameters\fP
.RS 4
\fIidx\fP Index on connection array 
.br
\fIsem\fP \fBSemaphore\fP to lock to avoid data races\&. 
.br
\fIcur_conn\fP Gets connection struct of connection array (idx position) 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBconnections\&.cpp\fP\&.
.SS "bool connections::is_all_connections_done ()\fC [inline]\fP"

.PP
Definition at line \fB96\fP of file \fBconnections\&.h\fP\&.
.SS "void connections::mark_obsolete (int idx)"

.PP
Definition at line \fB24\fP of file \fBconnections\&.cpp\fP\&.
.SS "int connections::register_new_conn (int nthread, int sd, sockaddr_in s_in, \fBSemaphore\fP & sem)"
Registers new connection on array\&.
.PP
\fBParameters\fP
.RS 4
\fInthread\fP Thread pair idx 
.br
\fIsd\fP \fBSocket\fP descriptor 
.br
\fIs_in\fP sockaddr_in info 
.br
\fIsem\fP \fBSemaphore\fP to lock to avoid data races\&. 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBconnections\&.cpp\fP\&.
.SS "int connections::unregister_conn (int idx, \fBSemaphore\fP & sem)"
Unregisters connection on array\&.
.PP
\fBParameters\fP
.RS 4
\fIidx\fP Index on connection array 
.br
\fIsem\fP \fBSemaphore\fP to lock to avoid data races\&. 
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBconnections\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconnection\fP* connections::current_connections {nullptr}\fC [private]\fP"

.PP
Definition at line \fB36\fP of file \fBconnections\&.h\fP\&.
.SS "int connections::first_free {0}\fC [private]\fP"

.PP
Definition at line \fB33\fP of file \fBconnections\&.h\fP\&.
.SS "bool connections::initialized {false}\fC [private]\fP"

.PP
Definition at line \fB32\fP of file \fBconnections\&.h\fP\&.
.SS "int connections::MaxConn {0}\fC [private]\fP"

.PP
Definition at line \fB35\fP of file \fBconnections\&.h\fP\&.
.SS "int connections::nThreads {0}\fC [private]\fP"

.PP
Definition at line \fB34\fP of file \fBconnections\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
