.TH "dispatch_cfg" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dispatch_cfg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dispatch_cfg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNumDispatch\fP"
.br
.ti -1c
.RI "std::string \fBIP\fP"
.br
.ti -1c
.RI "int \fBPort\fP"
.br
.ti -1c
.RI "int \fBNumThreads\fP"
.br
.ti -1c
.RI "std::string \fBTuxCliProg\fP"
.br
.ti -1c
.RI "std::string \fBTuxCliSetup\fP"
.br
.ti -1c
.RI "int \fBLogLevel\fP"
.br
.ti -1c
.RI "int \fBMaxConnections\fP"
.br
.ti -1c
.RI "int \fBStopTimeout\fP"
.br
.ti -1c
.RI "std::string \fBIpcFile\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBdispatch_cfg\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDispatcher\fP configuration 
.PP
Definition at line \fB37\fP of file \fBdispatch_cfg\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBdispatch_cfg\fP & v)\fC [friend]\fP"

.PP
Definition at line \fB49\fP of file \fBdispatch_cfg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string dispatch_cfg::IP"

.PP
Definition at line \fB39\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "std::string dispatch_cfg::IpcFile"

.PP
Definition at line \fB47\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::LogLevel"

.PP
Definition at line \fB44\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::MaxConnections"

.PP
Definition at line \fB45\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::NumDispatch"

.PP
Definition at line \fB38\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::NumThreads"

.PP
Definition at line \fB41\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::Port"

.PP
Definition at line \fB40\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "int dispatch_cfg::StopTimeout"

.PP
Definition at line \fB46\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "std::string dispatch_cfg::TuxCliProg"

.PP
Definition at line \fB42\fP of file \fBdispatch_cfg\&.h\fP\&.
.SS "std::string dispatch_cfg::TuxCliSetup"

.PP
Definition at line \fB43\fP of file \fBdispatch_cfg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
