.TH "src/getcfgfile.h" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/getcfgfile.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <json/json\&.h>\fP
.br
\fC#include <json/value\&.h>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGetCfgFile\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr char \fBsep\fP = '/'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr char sep = '/'\fC [constexpr]\fP"

.PP
Definition at line \fB19\fP of file \fBgetcfgfile\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
