.TH "src/ipclib.h" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ipclib.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'protocol_msg\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/ipc\&.h>\fP
.br
\fC#include <sys/shm\&.h>\fP
.br
\fC#include <sys/msg\&.h>\fP
.br
\fC#include <sys/sem\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIpc\fP"
.br
.ti -1c
.RI "union \fBsemun\fP"
.br
.ti -1c
.RI "class \fBSemaphore\fP"
.br
.ti -1c
.RI "class \fBSharedMemory\fP"
.br
.ti -1c
.RI "class \fBMessageQueue\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
