.TH "keep_running_flags" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keep_running_flags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <checker_pids\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBkeep_running_flags\fP ()"
.br
.ti -1c
.RI "\fB~keep_running_flags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fB_keep_accepting\fP {true}"
.br
.ti -1c
.RI "std::atomic< bool > \fB_keep_working\fP {true}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBchecker_pids\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "keep_running_flags::keep_running_flags ()\fC [inline]\fP"

.PP
Definition at line \fB39\fP of file \fBchecker_pids\&.h\fP\&.
.SS "keep_running_flags::~keep_running_flags ()\fC [inline]\fP"

.PP
Definition at line \fB40\fP of file \fBchecker_pids\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::atomic<bool> keep_running_flags::_keep_accepting {true}"

.PP
Definition at line \fB37\fP of file \fBchecker_pids\&.h\fP\&.
.SS "std::atomic<bool> keep_running_flags::_keep_working {true}"

.PP
Definition at line \fB38\fP of file \fBchecker_pids\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
