.TH "protopipe" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protopipe
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static constexpr char \fBWEAKUP_PIPE\fP [1] ={'1'}"
.br
.ti -1c
.RI "static constexpr char \fBENDING_PIPE\fP [1] ={'2'}"
.br
.ti -1c
.RI "static constexpr int \fBLEN_PIPEMSG\fP =1"
.br
.ti -1c
.RI "static char \fBGETPIPEMSG\fP [1]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr char protopipe::ENDING_PIPE[1] ={'2'}\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB7\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "char protopipe::GETPIPEMSG[1]\fC [static]\fP"

.PP
Definition at line \fB9\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "constexpr int protopipe::LEN_PIPEMSG =1\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB8\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "constexpr char protopipe::WEAKUP_PIPE[1] ={'1'}\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB6\fP of file \fBprotocol_msg\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
