.TH "protomsg::st_protomsg" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protomsg::st_protomsg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol_msg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmtype\fP {0}"
.br
.ti -1c
.RI "int \fBq_write\fP {0}"
.br
.ti -1c
.RI "int \fBterf\fP {0}"
.br
.ti -1c
.RI "int \fBterl\fP {0}"
.br
.ti -1c
.RI "int \fBidx\fP {0}"
.br
.ti -1c
.RI "char \fBguid\fP [10] {0}"
.br
.ti -1c
.RI "char \fBpid\fP [10] {0}"
.br
.ti -1c
.RI "char \fBaid\fP [8] {0}"
.br
.ti -1c
.RI "char \fBcabx\fP [8] {0}"
.br
.ti -1c
.RI "char \fBmsg\fP [1] {0}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBst_protomsg\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBprotocol_msg\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBst_protomsg\fP & v)\fC [friend]\fP"

.PP
Definition at line \fB31\fP of file \fBprotocol_msg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char protomsg::st_protomsg::aid[8] {0}"

.PP
Definition at line \fB27\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "char protomsg::st_protomsg::cabx[8] {0}"

.PP
Definition at line \fB28\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "char protomsg::st_protomsg::guid[10] {0}"

.PP
Definition at line \fB25\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "int protomsg::st_protomsg::idx {0}"

.PP
Definition at line \fB24\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "char protomsg::st_protomsg::msg[1] {0}"

.PP
Definition at line \fB29\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "long protomsg::st_protomsg::mtype {0}"

.PP
Definition at line \fB20\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "char protomsg::st_protomsg::pid[10] {0}"

.PP
Definition at line \fB26\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "int protomsg::st_protomsg::q_write {0}"

.PP
Definition at line \fB21\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "int protomsg::st_protomsg::terf {0}"

.PP
Definition at line \fB22\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "int protomsg::st_protomsg::terl {0}"

.PP
Definition at line \fB23\fP of file \fBprotocol_msg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
