.TH "protomsg" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protomsg
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBst_protomsg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static constexpr long \fBTYPE_WEAKUP_MSG\fP =1"
.br
.ti -1c
.RI "static constexpr long \fBTYPE_NORMAL_MSG\fP =2"
.br
.ti -1c
.RI "static constexpr long \fBTYPE_ENDING_MSG\fP =3"
.br
.ti -1c
.RI "static constexpr long \fBMAX_MSG_SIZE\fP =10000"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr long protomsg::MAX_MSG_SIZE =10000\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB17\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "constexpr long protomsg::TYPE_ENDING_MSG =3\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB16\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "constexpr long protomsg::TYPE_NORMAL_MSG =2\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB15\fP of file \fBprotocol_msg\&.h\fP\&.
.SS "constexpr long protomsg::TYPE_WEAKUP_MSG =1\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB14\fP of file \fBprotocol_msg\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
