.TH "Semaphore" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipclib\&.h>\fP
.PP
Inherits \fBIpc\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemaphore\fP (const key_t key, const int nsems, const int sem_val, bool deleteOnExit)"
.br
.ti -1c
.RI "\fBSemaphore\fP (int semid)"
.br
.ti -1c
.RI "\fBSemaphore\fP ()=default"
.br
.ti -1c
.RI "\fBSemaphore\fP (\fBSemaphore\fP const &)=default"
.br
.ti -1c
.RI "\fBSemaphore\fP (\fBSemaphore\fP &&)=default"
.br
.ti -1c
.RI "\fBSemaphore\fP & \fBoperator=\fP (\fBSemaphore\fP const &)=default"
.br
.ti -1c
.RI "\fBSemaphore\fP & \fBoperator=\fP (\fBSemaphore\fP &&)=default"
.br
.ti -1c
.RI "\fB~Semaphore\fP ()"
.br
.ti -1c
.RI "int \fBLock\fP ()"
.br
.ti -1c
.RI "int \fBUnlock\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBIpc\fP
.in +1c
.ti -1c
.RI "\fBIpc\fP ()=default"
.br
.ti -1c
.RI "\fBIpc\fP (key_t key, bool deleteOnExit)"
.br
.ti -1c
.RI "\fBIpc\fP (\fBIpc\fP const &)=default"
.br
.ti -1c
.RI "\fBIpc\fP (\fBIpc\fP &&)=default"
.br
.ti -1c
.RI "\fBIpc\fP & \fBoperator=\fP (\fBIpc\fP const &)=default"
.br
.ti -1c
.RI "\fBIpc\fP & \fBoperator=\fP (\fBIpc\fP &&)=default"
.br
.ti -1c
.RI "virtual \fB~Ipc\fP ()=default"
.br
.ti -1c
.RI "void \fBEnableDelete\fP ()"
.br
.ti -1c
.RI "void \fBDisableDelete\fP ()"
.br
.ti -1c
.RI "key_t \fBgetkey\fP () const"
.br
.ti -1c
.RI "int \fBgetid\fP () const"
.br
.ti -1c
.RI "int \fBgetflags\fP () const"
.br
.ti -1c
.RI "key_t \fBgetDeleteOnExit\fP () const"
.br
.ti -1c
.RI "void \fBsetkey\fP (key_t key)"
.br
.ti -1c
.RI "void \fBsetid\fP (int id)"
.br
.ti -1c
.RI "void \fBsetok\fP (bool ok)"
.br
.ti -1c
.RI "void \fBsetflags\fP (int flags)"
.br
.ti -1c
.RI "virtual \fBoperator bool\fP () const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "int \fBset\fP (const int op)"
.br
.ti -1c
.RI "int \fBget_stat\fP (int semid)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fB_nsems\fP"
.br
.ti -1c
.RI "std::vector< int > \fB_sem_val\fP"
.br
.ti -1c
.RI "struct sembuf \fB_sop\fP"
.br
.ti -1c
.RI "\fBsemun\fP \fB_st\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBLOCK\fP = \-1"
.br
.ti -1c
.RI "static constexpr int \fBUNLOCK\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSemaphore\fP Object IPC (\fBipclib\&.h\fP) 
.PP
Definition at line \fB107\fP of file \fBipclib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Semaphore::Semaphore (const key_t key, const int nsems, const int sem_val, bool deleteOnExit)"
\fBSemaphore\fP Constructor
.PP
\fBParameters\fP
.RS 4
\fIkey\fP (default IPC_PRIVATE) 
.br
\fInsems\fP =1 Number of semaphores 
.br
\fIsem_val\fP =1 Sempahore value 
.br
\fIdeleteOnExit\fP = false (don't remove semaphore on destruction\&. true = remove it) 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBipclib\&.cpp\fP\&.
.SS "Semaphore::Semaphore (int semid)"
\fBSemaphore\fP Constructor
.PP
\fBParameters\fP
.RS 4
\fIsemid\fP Id for an existing \fBSemaphore\fP 
.RE
.PP

.PP
Definition at line \fB10\fP of file \fBipclib\&.cpp\fP\&.
.SS "Semaphore::Semaphore ()\fC [default]\fP"

.SS "Semaphore::Semaphore (\fBSemaphore\fP const &)\fC [default]\fP"

.SS "Semaphore::Semaphore (\fBSemaphore\fP &&)\fC [default]\fP"

.SS "Semaphore::~Semaphore ()"

.PP
Definition at line \fB125\fP of file \fBipclib\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Semaphore::get_stat (int semid)\fC [private]\fP"

.PP
Definition at line \fB5\fP of file \fBipclib\&.cpp\fP\&.
.SS "int Semaphore::Lock ()\fC [inline]\fP"

.PP
Definition at line \fB145\fP of file \fBipclib\&.h\fP\&.
.SS "\fBSemaphore\fP & Semaphore::operator= (\fBSemaphore\fP &&)\fC [default]\fP"

.SS "\fBSemaphore\fP & Semaphore::operator= (\fBSemaphore\fP const &)\fC [default]\fP"

.SS "int Semaphore::set (const int op)\fC [private]\fP"

.PP
Definition at line \fB98\fP of file \fBipclib\&.cpp\fP\&.
.SS "int Semaphore::Unlock ()\fC [inline]\fP"

.PP
Definition at line \fB148\fP of file \fBipclib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Semaphore::_nsems\fC [private]\fP"

.PP
Definition at line \fB109\fP of file \fBipclib\&.h\fP\&.
.SS "std::vector<int> Semaphore::_sem_val\fC [private]\fP"

.PP
Definition at line \fB110\fP of file \fBipclib\&.h\fP\&.
.SS "struct sembuf Semaphore::_sop\fC [private]\fP"

.PP
Definition at line \fB111\fP of file \fBipclib\&.h\fP\&.
.SS "\fBsemun\fP Semaphore::_st\fC [private]\fP"

.PP
Definition at line \fB112\fP of file \fBipclib\&.h\fP\&.
.SS "constexpr int Semaphore::LOCK = \-1\fC [static]\fP, \fC [constexpr]\fP, \fC [private]\fP"

.PP
Definition at line \fB113\fP of file \fBipclib\&.h\fP\&.
.SS "constexpr int Semaphore::UNLOCK = 1\fC [static]\fP, \fC [constexpr]\fP, \fC [private]\fP"

.PP
Definition at line \fB114\fP of file \fBipclib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
