.TH "semun" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipclib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct semid_ds * \fBbuf\fP"
.br
.ti -1c
.RI "unsigned short int * \fBarray\fP"
.br
.ti -1c
.RI "struct seminfo * \fB__buf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB95\fP of file \fBipclib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct seminfo* semun::__buf"

.PP
Definition at line \fB99\fP of file \fBipclib\&.h\fP\&.
.SS "unsigned short int* semun::array"

.PP
Definition at line \fB98\fP of file \fBipclib\&.h\fP\&.
.SS "struct semid_ds* semun::buf"

.PP
Definition at line \fB97\fP of file \fBipclib\&.h\fP\&.
.SS "int semun::val"

.PP
Definition at line \fB96\fP of file \fBipclib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
