.TH "socket_data_t" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread_pair\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBsocket_data_t\fP &c) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsd\fP"
.br
.ti -1c
.RI "sockaddr_in \fBsockaddr\fP"
.br
.ti -1c
.RI "int \fBidx_con\fP"
.br
.ti -1c
.RI "std::string \fBrcvinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBthread_pair\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool socket_data_t::operator== (const \fBsocket_data_t\fP & c) const\fC [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBthread_pair\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int socket_data_t::idx_con"

.PP
Definition at line \fB36\fP of file \fBthread_pair\&.h\fP\&.
.SS "std::string socket_data_t::rcvinfo"

.PP
Definition at line \fB37\fP of file \fBthread_pair\&.h\fP\&.
.SS "int socket_data_t::sd"

.PP
Definition at line \fB34\fP of file \fBthread_pair\&.h\fP\&.
.SS "sockaddr_in socket_data_t::sockaddr"

.PP
Definition at line \fB35\fP of file \fBthread_pair\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
