.TH "TuxClient" 3 "Wed May 10 2023" "Version 01.00" "Dispatcher TCP/IP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TuxClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTuxClient\fP (int idx, \fBMessageQueue\fP &queue)"
.br
.ti -1c
.RI "int \fBoperator()\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBidx_cli\fP {0}"
.br
.ti -1c
.RI "\fBMessageQueue\fP & \fBcommon_queue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBtuxcli_main\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TuxClient::TuxClient (int idx, \fBMessageQueue\fP & queue)\fC [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBtuxcli_main\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int TuxClient::operator() ()"

.PP
Definition at line \fB47\fP of file \fBtuxcli_main\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMessageQueue\fP& TuxClient::common_queue\fC [private]\fP"

.PP
Definition at line \fB41\fP of file \fBtuxcli_main\&.cpp\fP\&.
.SS "int TuxClient::idx_cli {0}\fC [private]\fP"

.PP
Definition at line \fB40\fP of file \fBtuxcli_main\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dispatcher TCP/IP from the source code\&.
